# Generated by Django 6.0.4 on 2026-05-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('psu', 'Блок питания'), ('gpu', 'Видеокарта')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['component_type', 'component_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ценовая категория',
                'verbose_name_plural': 'Ценовые категории',
                'ordering': ['min_price'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption', models.IntegerField()),
                ('power_connectors', models.CharField(blank=True, max_length=100)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='core.component')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(choices=[('LGA1700', 'LGA1700'), ('LGA1200', 'LGA1200'), ('AM5', 'AM5'), ('AM4', 'AM4')], max_length=20)),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('memory_slots', models.IntegerField(default=2)),
                ('supports_integrated_graphics', models.BooleanField(default=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='core.component')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.IntegerField()),
                ('efficiency_cert', models.CharField(blank=True, choices=[('', 'Без сертификата'), ('80Plus', '80 Plus'), ('Bronze', '80 Plus Bronze'), ('Silver', '80 Plus Silver'), ('Gold', '80 Plus Gold'), ('Platinum', '80 Plus Platinum'), ('Titanium', '80 Plus Titanium')], default='', max_length=20)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powersupply', to='core.component')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='core.pricecategory'),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(choices=[('LGA1700', 'LGA1700'), ('LGA1200', 'LGA1200'), ('AM5', 'AM5'), ('AM4', 'AM4')], max_length=20)),
                ('tdp', models.IntegerField()),
                ('has_integrated_graphics', models.BooleanField(default=False)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='core.component')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('capacity_gb', models.IntegerField(choices=[(4, '4 ГБ'), (8, '8 ГБ'), (16, '16 ГБ'), (32, '32 ГБ'), (64, '64 ГБ')])),
                ('frequency_mhz', models.IntegerField(blank=True, null=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='core.component')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Incompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('component_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_1', to='core.component')),
                ('component_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_2', to='core.component')),
            ],
            options={
                'verbose_name': 'Несовместимость',
                'verbose_name_plural': 'Несовместимости',
                'unique_together': {('component_1', 'component_2')},
            },
        ),
    ]
