# Generated by Django 6.0.4 on 2026-05-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('processor', 'Процессор'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('psu', 'Блок питания'), ('gpu', 'Видеокарта')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['component_type', 'component_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ценовая категория',
                'verbose_name_plural': 'Ценовые категории',
                'ordering': ['min_price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption', models.IntegerField()),
                ('power_connectors', models.CharField(blank=True, max_length=100)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu', to='core.component')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.component')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(choices=[('LGA1700', 'LGA1700'), ('LGA1200', 'LGA1200'), ('AM5', 'AM5'), ('AM4', 'AM4')], max_length=20)),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('memory_slots', models.IntegerField(default=2)),
                ('supports_integrated_graphics', models.BooleanField(default=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='core.component')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.IntegerField()),
                ('efficiency_cert', models.CharField(blank=True, choices=[('', 'Без сертификата'), ('80Plus', '80 Plus'), ('Bronze', '80 Plus Bronze'), ('Silver', '80 Plus Silver'), ('Gold', '80 Plus Gold'), ('Platinum', '80 Plus Platinum'), ('Titanium', '80 Plus Titanium')], default='', max_length=20)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powersupply', to='core.component')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='core.pricecategory'),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(choices=[('LGA1700', 'LGA1700'), ('LGA1200', 'LGA1200'), ('AM5', 'AM5'), ('AM4', 'AM4')], max_length=20)),
                ('tdp', models.IntegerField()),
                ('has_integrated_graphics', models.BooleanField(default=False)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='core.component')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=10)),
                ('capacity_gb', models.IntegerField(choices=[(4, '4 ГБ'), (8, '8 ГБ'), (16, '16 ГБ'), (32, '32 ГБ'), (64, '64 ГБ')])),
                ('frequency_mhz', models.IntegerField(blank=True, null=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='core.component')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compatible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motherboard')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.powersupply')),
                ('price_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pricecategory')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.processor')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ram')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('component_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_1', to='core.component')),
                ('component_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incompatibilities_as_2', to='core.component')),
            ],
            options={
                'verbose_name': 'Несовместимость',
                'verbose_name_plural': 'Несовместимости',
                'unique_together': {('component_1', 'component_2')},
            },
        ),
    ]
